# Generated by Django 5.1.2 on 2024-10-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='full_name',
            new_name='user',
        ),
    ]
