# Generated by Django 5.1.2 on 2024-10-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0004_rename_job_vlxd_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_vlxd',
            field=models.BooleanField(default=False),
        ),
    ]
