# Generated by Django 5.1.2 on 2024-10-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0005_member_is_vlxd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_indivdual',
            new_name='is_individual',
        ),
    ]
