# Generated by Django 5.1.2 on 2024-10-28 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0007_alter_individual_phone_alter_organization_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='c_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_num',
            field=models.CharField(max_length=10, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='vlxd',
            name='c_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Company Name'),
        ),
    ]
