# Generated by Django 5.1.2 on 2024-10-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0008_alter_organization_c_name_alter_organization_tax_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='c_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EOB.member', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='vlxd',
            name='c_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EOB.member', verbose_name='Company Name'),
        ),
    ]
