# Generated by Django 5.1.2 on 2024-10-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0009_alter_organization_c_name_alter_vlxd_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='vlxd',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Company Name'),
        ),
    ]
