# Generated by Django 5.1.2 on 2024-11-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0013_alter_individual_email_alter_organization_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vlxd',
            old_name='c_name',
            new_name='name',
        ),
    ]
