# Generated by Django 5.1.2 on 2024-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0016_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Posted by'),
        ),
    ]
