# Generated by Django 5.1.2 on 2024-12-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0017_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/media'),
        ),
    ]
