# Generated by Django 5.1.2 on 2024-12-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0023_folder_post_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='can_have_posts',
            field=models.BooleanField(default=True),
        ),
    ]
