# Generated by Django 5.1.2 on 2024-12-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EOB', '0024_folder_can_have_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='can_have_posts',
            field=models.BooleanField(default=False),
        ),
    ]
